### ISSUE TITLE
Dev Home Github OAuth app should be updated to Modern app

### ISSUE THREAD

**Issue by vineeththomasalex** [microsoft/devhomegithubextension#122]
### Description of the new feature / enhancement

Currently Dev Home uses a GitHub OAuth app. Per jeffwilcox in https://github.com/microsoft/github-operations/issues/252 , the Github Modern app is more appropriate for better app management. 

This does not block any functionality for DevHome currently, but aids in long term management of the Github app.

**Comment by mikebattista** [comment]
We need to make sure we don't regress any user experience/functionality if we switch. From https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/differences-between-github-apps-and-oauth-apps for example,

> There is one case where an OAuth App is preferred over a GitHub App. If your app needs to access enterprise resources, you should use an OAuth App because a GitHub App cannot yet be given permissions against an enterprise.

Losing functionality like this would be a non-starter. We started as an OAuth app since all other clients are OAuth apps and the proven model reduces risk. Happy to explore the GitHub App approach, if we can be sure we don't regress anything.
