### ISSUE TITLE
Support custom GitHub issue queries

### ISSUE THREAD

**Issue by patrickklaeren** [microsoft/devhomegithubextension#154]
### Suggested new feature or improvement

Whilst there is a GitHub widget and it allows for you to query repositories, pull requests and assigned items, it does not allow you to add a custom query link for all issues/pull requests.

### Scenario

In an organization, I may choose to see all open pull requests or issues collated by a certain user or number of variables.

I want to see a widget that collates the following query, for example:

```
https://github.com/issues?q=is%3Aissue+user%3Afoobar+no%3Aproject+is%3Aopen
```

**Comment by patrickklaeren** [comment]
Yes - as I'd like to be able to add this URL for example:

[https://github.com/issues?q=is%3Aissue+user%3Afoobar+no%3Aproject+is%3Aopen](https://github.com/issues?q=is%3Aissue+user%3Afoobar+no%3Aproject+is%3Aopen+sort%3Aupdated-desc)

And it show the relevant issues from that query.

**Comment by cinnamon-msft** [comment]
I believe this has been fixed. If you're still not able to get this working, please let us know!

**Comment by krschau** [comment]
Reading this again, I actually think it's a duplicate of #245

**Comment by tebeco** [comment]
> Reading this again, I actually think it's a duplicate of #245. (Or, technically, that one is a duplicate of this one).

hello @krschau,

Just to satisfy my curiousity, and for later ticket, what's the rule for closing a from:
![image](https://github.com/microsoft/devhomegithubextension/assets/2266487/0b046056-23b9-4b49-a9a4-cf090c805158)

with people following the ticket possibly.

in favor of:
![image](https://github.com/microsoft/devhomegithubextension/assets/2266487/6d12ba17-9e93-43d0-971f-f704aae91b25)

I generally see other repository on github closing newly created issue and favor old one generally tracked.

Now I'm a bit confused as I received the notification:
* closed
* probably fixed (but not clear it is fixed)
* is a duplicated (while it was not a duplicate at that time)
* like to a recent ticket (the duplicate)
* that duplicate it not indicated as the problem is solved.

**Comment by krschau** [comment]
Hi @tebeco. That's a valid question. Generally, we do close the newer one, and you make a great point about if people are already following that original ticket. The reason I kept the newer one in this instance was that it was clearer what the bug actually was -- as you can see from the complicated history of this issue, there was some misunderstanding about what the issue was. At the end of the day, we're human and sometimes make mistakes when triaging issues, but we try to rectify it when we find a mistake.
