### ISSUE TITLE
Feature Request: Auto-Update Github Widgets

### ISSUE THREAD

**Issue by rencendant** [microsoft/devhomegithubextension#251]
### Suggested new feature or improvement

I would like to see the feature wherein GitHub widgets are automatically updating everytime I open the dev home app.

### Scenario

This feature could be used when monitoring github-related widgets like issues, pull requests, assigned to me, etc. when opening the dev home app.

**Comment by dkbennett** [comment]
The widgets already refresh every 5 minutes while devhome is open, and they trigger a refresh when they are created on a fresh launch of DevHome as well. I'm not sure what the ask is here, as they already refresh when opening devhome.

I suspect what you are seeing is actually the widgets not removing old data properly and the symptom is that they appear to not refresh. They _are_ refreshing, they just aren't properly removing stale data. That issue is #221 and has a fix in PR.  Going to close this one as a duplicate of that one.
